UPDATE document_templates
SET content_profile = COALESCE(content_profile, '{}'::jsonb) || 
  jsonb_build_object('pdf_mappings', '{
    "Given Name(s)": ["reg_names"],
    "First Surname": ["reg_1_surname"],
    "Second Surname": ["reg_2_surname"],
    "nombres": ["reg_names"],
    "primer_apellido": ["reg_1_surname"],
    "segundo_apellido": ["reg_2_surname"],
    "NUIP": ["nuip"],
    "nuip": ["nuip"],
    "Sex": ["sex"],
    "sexo": ["sex"],
    "Blood Type": ["blood_type"],
    "grupo_sanguineo": ["blood_type"],
    "Rh Factor": ["rh_factor"],
    "factor_rh": ["rh_factor"],
    "Father''s Surnames and Full Names": ["father_surnames_names"],
    "Mother''s Surnames and Full Names": ["mother_surnames_names"],
    "Father''s Identification Document": ["father_id_doc"],
    "Mother''s Identification Document": ["mother_id_doc"],
    "Father''s Nationality": ["father_nationality"],
    "Mother''s Nationality": ["mother_nationality"],
    "padre_nombres": ["father_surnames_names"],
    "madre_nombres": ["mother_surnames_names"],
    "padre_apellidos": ["father_surnames_names"],
    "madre_apellidos": ["mother_surnames_names"],
    "padre_identificacion": ["father_id_doc"],
    "madre_identificacion": ["mother_id_doc"],
    "Declarant''s Surnames and Full Names": ["declarant_surnames_names"],
    "Declarant''s Identification Document": ["declarant_id_doc"],
    "First Witness''s Surnames and Full Names": ["witness1_surnames_names"],
    "First Witness''s Identification Document": ["witness1_id_doc"],
    "Second Witness''s Surnames and Full Names": ["witness2_surnames_names"],
    "Second Witness''s Identification Document": ["witness2_id_doc"],
    "Notary Number": ["notary_number"],
    "numero_oficina": ["notary_number"],
    "Code": ["reg_code"],
    "codigo": ["reg_code"],
    "Serial Indicator": ["serial_indicator"],
    "serial": ["serial_indicator"],
    "Live Birth Certificate Number": ["birth_cert_number"],
    "acta": ["birth_cert_number"],
    "Notes": ["notes1"],
    "notas": ["notes1"],
    "Place of Birth": ["birth_country_dept_munic"],
    "lugar_nacimiento": ["birth_country_dept_munic"],
    "Country - Department - Municipality - Township and/or Police Station": ["country_dept_munic"],
    "Date of Birth": ["birth_day", "birth_month", "birth_year"],
    "fecha_nacimiento": ["birth_day", "birth_month", "birth_year"],
    "Date Registered": ["reg_day", "reg_month", "reg_year"],
    "fecha_registro": ["reg_day", "reg_month", "reg_year"]
  }'::jsonb);
